attitude_feedback:

  default_gains:

    # influences pitching and rolling
    horizontal:
      attitude:
        kq: 8.0
        kw: 0.0

    # influences yawing
    vertical:
      attitude:
        kq: 4.0
        kw: 10.0

mass_estimator:
  km: 1.0
  km_lim: 10.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
